### ISSUE TITLE
Better error message when ZIP archive is broken

### ISSUE THREAD

**Issue by szpak** [ysb33r/gradleTest#28]
In a situation when available file is corrupted (e.g. when the fist execution of gradleTest plugin was aborted while downloading) the subsequent executions fail with not much meaning full exception:

```
:gradleDistributionDownloader FAILED
:gradleDistributionDownloader (Thread[Daemon worker,5,main]) completed. Took 5 mins 40.563 secs.

FAILURE: Build failed with an exception.

* What went wrong:
java.lang.NullPointerException (no error message)

* Try:
Run with --debug option to get more log output.

* Exception is:
java.lang.NullPointerException
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2015)
	at org.ysb33r.gradle.gradletest.internal.AvailableDistributionsInternal.addDistributions(AvailableDistributionsInternal.groovy:65)
	at org.ysb33r.gradle.gradletest.AvailableDistributions$addDistributions.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.ysb33r.gradle.gradletest.GradleTestPlugin$1.afterExecute(GradleTestPlugin.groovy:103)
```

After some debugging I get know it is caused by the `ZipException: error in opening zip file` exception thrown in GradleTestDownloader.groovy:132 (`Unpacker.unpackTo()`). However it exception is not reported as just after in a `afterExecute` block GradleTestPlugin:103 `addDistricutions(downloader.downloaded)` method is called with `null` (set by default) which results in aforementioned NPE which hides original reason. As as workaround I propose to set `downloaded` to `[]` which allows `afterExecute` to pass and fail the task with `ZipException`.

**Comment by ysb33r** [comment]
FIxed in v0.5.5 release.
