### ISSUE TITLE
'No distribution is available for version X.XX' error on gradleTest rerun

### ISSUE THREAD

**Issue by szpak** [ysb33r/gradleTest#32]
When I rerun `gradleTest` (with `downloadToGradleUserHome = false`) there is the following exception thrown, even though the first execution finished successfully and there appropriate zip file in `build/gradleDist`. It is needed to remove `gradleDist` to make it work again.

```
* What went wrong:
Execution failed for task ':gradleTest'.
> No distribution is available for version '2.11'
(...)
* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':gradleTest'.
    (...)
    at org.ysb33r.gradle.gradletest.GradleTest$_exec_closure4.doCall(GradleTest.groovy:135)
    (...)
    at org.ysb33r.gradle.gradletest.GradleTest.exec(GradleTest.groovy:132)
    (...)
Caused by: java.io.FileNotFoundException: No distribution is available for version '2.11'
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:80)
    at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:74)
    at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:84)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:247)
    ... 102 more
```

**Comment by szpak** [comment]
It happens only for versions different than Gradle version used to execute the main script. As I debugged it looks like the plugin takes into account only version located in the default Gradle directory only, while that given version was already downloaded in the previous run and is available in `build/gradleDist`.

**Comment by ysb33r** [comment]
Fancy trying this with 1.0-beta1 release? (README is on the `RELEASE_1_0_BETA1` tag).

**Comment by ysb33r** [comment]
I assume this is good now.
