### ISSUE TITLE
Fix various deprecation messages with Gradle 4.x

### ISSUE THREAD

**Issue by bmuschko** [ysb33r/gradleTest#78]
The plugin emits multiple deprecation message with the use of Gradle 4.x.

```
The setTestClassesDir(File) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use the setTestClassesDirs(FileCollection) method instead.
        at org.gradle.api.tasks.testing.Test.setTestClassesDir(Test.java:956)
        at org.ysb33r.gradle.gradletest.GradleTest_Decorated.setTestClassesDir(Unknown Source)
```

```
The ConfigurableReport.setDestination(Object) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use the method ConfigurableReport.setDestination(File) instead.
        at org.gradle.api.reporting.internal.SimpleReport.setDestination(SimpleReport.java:76)
        at org.gradle.api.reporting.internal.TaskGeneratedSingleDirectoryReport_Decorated.setDestination(Unknown Source)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.invokeMethod(BeanDynamicObject.java:479)
        at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.setProperty(BeanDynamicObject.java:358)
        at org.gradle.internal.metaobject.BeanDynamicObject.trySetProperty(BeanDynamicObject.java:176)
        at org.gradle.internal.metaobject.CompositeDynamicObject.trySetProperty(CompositeDynamicObject.java:66)
        at org.gradle.internal.metaobject.AbstractDynamicObject.setProperty(AbstractDynamicObject.java:73)
        at org.gradle.api.reporting.internal.TaskGeneratedSingleDirectoryReport_Decorated.setProperty(Unknown Source)
        at org.codehaus.groovy.runtime.InvokerHelper.setProperty(InvokerHelper.java:197)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.setProperty(ScriptBytecodeAdapter.java:484)
        at org.ysb33r.gradle.gradletest.GradleTest.setHtmlReportFolder(GradleTest.groovy:213)
        at org.ysb33r.gradle.gradletest.GradleTest.<init>(GradleTest.groovy:50)
        at org.ysb33r.gradle.gradletest.GradleTest_Decorated.<init>(Unknown Source)
```

**Comment by bmuschko** [comment]
Any chance you could create a new version with a fix for the deprecation message?

**Comment by ysb33r** [comment]
@bmuschko Will release the update shortly. I am curious though, why you are seeing those deprecation message. The fixes are in an area that will only executing when `org.ysb33r.gradletest` is applied, but the guides plugin never applies that - it uses `org.ysb33r.gradlerunner` instead.

**Comment by bmuschko** [comment]
The plugin uses `org.ysb33r.gradletest` [in its own build script](https://github.com/gradle-guides/gradle-guides-plugin/blob/master/build.gradle#L7).

**Comment by ysb33r** [comment]
> The plugin uses org.ysb33r.gradletest in its own build script.

Of course!

**Comment by ysb33r** [comment]
@bmuschko Please update to 1.0-beta12.

**Comment by bmuschko** [comment]
Thanks, that does the job!
