### ISSUE TITLE
Custom sourcesets don't seem to work

### ISSUE THREAD

**Issue by scphantm** [ysb33r/gradleTest#87]
here is my log, the interesting part is the 4 lines at the top where they "file or directory '/src/main/libertyConfig', not found".  Those folders are there in the right place under the build folder, but the test can't find them.  Those folders are custom sourcesets i created.  The only odd thing i can find is the fact that manifest file thats generated by you lists the java and groovy folders, but not the two custom sourceset that i created

you can see this project here

https://github.com/hmhs/ci.gradle/tree/v2

branch v2 is where im working.  Its rough i know, i just started on the testing.  But this is the log file its giving me

```
org.gradle.testkit.runner.UnexpectedBuildFailure: Unexpected build execution failure in /Users/scphantm/Code/hmhs/ci.gradle/build/gradleTest/Deploy-multi-configBasedGroovyDSL/4.3.1 with arguments [runGradleTest, --init-script, /Users/scphantm/Code/hmhs/ci.gradle/build/gradleTest/init.gradle, --full-stacktrace, --info, --console=plain]

Output:
The client will now receive all logging from the daemon (pid: 84090). The daemon log file: /var/folders/tv/2pxv_1sd2xs2z47ws4xjc46w0000gn/T/.gradle-test-kit-scphantm/test-kit-daemon/4.3.1/daemon-84090.out.log
Starting build in new daemon [memory: 954.7 MB]
Closing daemon's stdin at end of input.
The daemon will no longer process any standard input.
Using 8 worker leases.
Creating new cache for fileHashes, path /private/var/folders/tv/2pxv_1sd2xs2z47ws4xjc46w0000gn/T/.gradle-test-kit-scphantm/caches/4.3.1/fileHashes/fileHashes.bin, access org.gradle.cache.internal.DefaultCacheAccess@530751fc
Creating new cache for resourceHashesCache, path /private/var/folders/tv/2pxv_1sd2xs2z47ws4xjc46w0000gn/T/.gradle-test-kit-scphantm/caches/4.3.1/fileHashes/resourceHashesCache.bin, access org.gradle.cache.internal.DefaultCacheAccess@530751fc
Creating new cache for fileHashes, path /Users/scphantm/Code/hmhs/ci.gradle/build/gradleTest/Deploy-multi-configBasedGroovyDSL/4.3.1/.gradle/4.3.1/fileHashes/fileHashes.bin, access org.gradle.cache.internal.DefaultCacheAccess@539b2476
Creating new cache for plugin-use-metadata, path /private/var/folders/tv/2pxv_1sd2xs2z47ws4xjc46w0000gn/T/.gradle-test-kit-scphantm/caches/4.3.1/plugin-resolution/plugin-use-metadata.bin, access org.gradle.cache.internal.DefaultCacheAccess@4bcb18b2
Creating new cache for client-status, path /private/var/folders/tv/2pxv_1sd2xs2z47ws4xjc46w0000gn/T/.gradle-test-kit-scphantm/caches/4.3.1/plugin-resolution/client-status.bin, access org.gradle.cache.internal.DefaultCacheAccess@4bcb18b2
Starting Build
Settings evaluated using settings file '/Users/scphantm/Code/hmhs/ci.gradle/build/gradleTest/Deploy-multi-configBasedGroovyDSL/4.3.1/settings.gradle'.
Projects loaded. Root project using build file '/Users/scphantm/Code/hmhs/ci.gradle/build/gradleTest/Deploy-multi-configBasedGroovyDSL/4.3.1/build.gradle'.
Included projects: [root project '4.3.1']
Creating new cache for metadata-1.1/results, path /private/var/folders/tv/2pxv_1sd2xs2z47ws4xjc46w0000gn/T/.gradle-test-kit-scphantm/caches/transforms-1/metadata-1.1/results.bin, access org.gradle.cache.internal.DefaultCacheAccess@338c614b
Evaluating root project '4.3.1' using build file '/Users/scphantm/Code/hmhs/ci.gradle/build/gradleTest/Deploy-multi-configBasedGroovyDSL/4.3.1/build.gradle'.
file or directory '/src/main/libertyConfig', not found
file or directory '/src/main/libertyConfig', not found
file or directory '/src/main/libertyConfig', not found
file or directory '/src/main/libertyConfig', not found
All projects evaluated.
Selected primary task 'runGradleTest' from project :
Creating new cache for annotation-processors, path /Users/scphantm/Code/hmhs/ci.gradle/build/gradleTest/Deploy-multi-configBasedGroovyDSL/4.3.1/.gradle/4.3.1/fileContent/annotation-processors.bin, access org.gradle.cache.internal.DefaultCacheAccess@71edfd83
The server configFile was configured but was not found at: /src/main/libertyConfig/server.xml
The server.env was configured but was not found at: /src/main/libertyConfig/server.env
The jvm.options was configured but was not found at: /src/main/libertyConfig/jvm.options
Tasks to be executed: [task ':installLiberty', task ':libertyCreateAnt', task ':libertyCreateBootstrap', task ':libertyCreateJvmOptions', task ':libertyCreateServerEnv', task ':libertyCreateServerXml', task ':libertyCreateConfig', task ':libertyCreate', task ':compileJava', task ':processResources', task ':classes', task ':war', task ':installApps', task ':libertyStart', task ':printMessageAboutRunningServer', task ':libertyStop', task ':runGradleTest']
Creating new cache for resourceHashesCache, path /Users/scphantm/Code/hmhs/ci.gradle/build/gradleTest/Deploy-multi-configBasedGroovyDSL/4.3.1/.gradle/4.3.1/fileHashes/resourceHashesCache.bin, access org.gradle.cache.internal.DefaultCacheAccess@539b2476
Creating new cache for taskHistory, path /Users/scphantm/Code/hmhs/ci.gradle/build/gradleTest/Deploy-multi-configBasedGroovyDSL/4.3.1/.gradle/4.3.1/taskHistory/taskHistory.bin, access org.gradle.cache.internal.DefaultCacheAccess@5291643
Creating new cache for outputFiles, path /Users/scphantm/Code/hmhs/ci.gradle/build/gradleTest/Deploy-multi-configBasedGroovyDSL/4.3.1/.gradle/buildOutputCleanup/outputFiles.bin, access org.gradle.cache.internal.DefaultCacheAccess@13939b62
:installLiberty (Thread[Task worker for ':' Thread 6,5,main]) started.
:installLiberty
Putting task artifact state for task ':installLiberty' into context took 0.001 secs.
Up-to-date check for task ':installLiberty' took 0.0 secs. It is not up-to-date because:
  Task has not declared any outputs.
[ant:get] Getting: http://repo1.maven.org/maven2/com/ibm/websphere/appserver/runtime/wlp-webProfile7/17.0.0.1/wlp-webProfile7-17.0.0.1.zip
[ant:get] To: /var/folders/tv/2pxv_1sd2xs2z47ws4xjc46w0000gn/T/wlp-cache/wlp-webProfile7-17.0.0.1.zip
[ant:get] Not modified - so not downloaded
:installLiberty (Thread[Task worker for ':' Thread 6,5,main]) completed. Took 1.193 secs.
:libertyCreateAnt (Thread[Task worker for ':' Thread 6,5,main]) started.
:libertyCreateAnt
Putting task artifact state for task ':libertyCreateAnt' into context took 0.0 secs.
Up-to-date check for task ':libertyCreateAnt' took 0.0 secs. It is not up-to-date because:
  Task has not declared any outputs.
[ant:server] CWWKM2001I: server.config.dir is /Users/scphantm/Code/hmhs/ci.gradle/build/gradleTest/Deploy-multi-configBasedGroovyDSL/4.3.1/build/wlp/usr/servers/LibertyProjectServer.
[ant:server] CWWKM2001I: server.output.dir is /Users/scphantm/Code/hmhs/ci.gradle/build/gradleTest/Deploy-multi-configBasedGroovyDSL/4.3.1/build/wlp/usr/servers/LibertyProjectServer.
[ant:server] CWWKM2001I: Invoke command is [/Users/scphantm/Code/hmhs/ci.gradle/build/gradleTest/Deploy-multi-configBasedGroovyDSL/4.3.1/build/wlp/bin/server, create, LibertyProjectServer].
[ant:server] objc[84096]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/bin/java (0x1053504c0) and /Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/lib/libinstrument.dylib (0x10546b4e0). One of the two will be used. Which one is undefined.
[ant:server] Server LibertyProjectServer created.
:libertyCreateAnt (Thread[Task worker for ':' Thread 6,5,main]) completed. Took 0.365 secs.
:libertyCreateBootstrap (Thread[Task worker for ':' Thread 6,5,main]) started.
:libertyCreateBootstrap
Putting task artifact state for task ':libertyCreateBootstrap' into context took 0.003 secs.
Default bootstrap.properties file not found at: /src/main/libertyConfig/bootstrap.properties
Default bootstrap.properties file not found at: /src/main/libertyConfig/bootstrap.properties
Up-to-date check for task ':libertyCreateBootstrap' took 0.011 secs. It is not up-to-date because:
  No history is available.
Default bootstrap.properties file not found at: /src/main/libertyConfig/bootstrap.properties
:libertyCreateBootstrap (Thread[Task worker for ':' Thread 6,5,main]) completed. Took 0.03 secs.
:libertyCreateJvmOptions (Thread[Task worker for ':' Thread 6,5,main]) started.
:libertyCreateJvmOptions
Putting task artifact state for task ':libertyCreateJvmOptions' into context took 0.0 secs.
The jvm.options was configured but was not found at: /src/main/libertyConfig/jvm.options
The jvm.options was configured but was not found at: /src/main/libertyConfig/jvm.options
Up-to-date check for task ':libertyCreateJvmOptions' took 0.0 secs. It is not up-to-date because:
  No history is available.
The jvm.options was configured but was not found at: /src/main/libertyConfig/jvm.options
:libertyCreateJvmOptions (Thread[Task worker for ':' Thread 6,5,main]) completed. Took 0.003 secs.
:libertyCreateServerEnv (Thread[Task worker for ':' Thread 5,5,main]) started.
:libertyCreateServerEnv
Putting task artifact state for task ':libertyCreateServerEnv' into context took 0.0 secs.
Deleting stale output file: /Users/scphantm/Code/hmhs/ci.gradle/build/gradleTest/Deploy-multi-configBasedGroovyDSL/4.3.1/build/wlp/usr/servers/LibertyProjectServer/server.env
The server.env was configured but was not found at: /src/main/libertyConfig/server.env
The server.env was configured but was not found at: /src/main/libertyConfig/server.env
Up-to-date check for task ':libertyCreateServerEnv' took 0.001 secs. It is not up-to-date because:
  No history is available.
The server.env was configured but was not found at: /src/main/libertyConfig/server.env
:libertyCreateServerEnv (Thread[Task worker for ':' Thread 5,5,main]) completed. Took 0.005 secs.
:libertyCreateServerXml (Thread[Task worker for ':' Thread 5,5,main]) started.
:libertyCreateServerXml
Putting task artifact state for task ':libertyCreateServerXml' into context took 0.0 secs.
Deleting stale output file: /Users/scphantm/Code/hmhs/ci.gradle/build/gradleTest/Deploy-multi-configBasedGroovyDSL/4.3.1/build/wlp/usr/servers/LibertyProjectServer/server.xml
The server configFile was configured but was not found at: /src/main/libertyConfig/server.xml
:libertyCreateServerXml FAILED
:libertyCreateServerXml (Thread[Task worker for ':' Thread 5,5,main]) completed. Took 0.006 secs.

FAILURE: Build failed with an exception.

* What went wrong:
A problem was found with the configuration of task ':libertyCreateServerXml'.
> File '/src/main/libertyConfig/server.xml' specified for property 'serverXmlFile' does not exist.

* Try:
Run with --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskValidationException: A problem was found with the configuration of task ':libertyCreateServerXml'.
	at org.gradle.api.internal.tasks.TaskValidationContext$Severity$2.report(TaskValidationContext.java:54)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:55)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:97)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:87)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:626)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:581)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.gradle.api.InvalidUserDataException: File '/src/main/libertyConfig/server.xml' specified for property 'serverXmlFile' does not exist.
	at org.gradle.api.internal.tasks.TaskValidationContext$Severity$2.report(TaskValidationContext.java:51)
	... 28 more


* Get more help at https://help.gradle.org

BUILD FAILED in 5s
6 actionable tasks: 6 executed

	at org.gradle.testkit.runner.internal.DefaultGradleRunner$1.execute(DefaultGradleRunner.java:237)
	at org.gradle.testkit.runner.internal.DefaultGradleRunner$1.execute(DefaultGradleRunner.java:234)
	at org.gradle.testkit.runner.internal.DefaultGradleRunner.run(DefaultGradleRunner.java:298)
	at org.gradle.testkit.runner.internal.DefaultGradleRunner.build(DefaultGradleRunner.java:234)
	at gradleTest.tests.Deploy_multi_configBasedGroovyDSLCompatibilitySpec.Deploy-multi-configBasedGroovyDSL : #version(Deploy-multi-configBasedGroovyDSLCompatibilitySpec.groovy:134)
```

**Comment by scphantm** [comment]
ive dug deeper on this one, i'm not convinced its a gradletest problem, i think it may be more of a gradle issue.  it looks like when gradle is resolving input annotations, it is trying to find the sourceset folder in relation to the working folder, but something is screwy in that and its not finding it.  im not closing this yet, but thats what i think so far.

**Comment by scphantm** [comment]
thats what i noticed in the first place as well, problem is they do exist.  I think gradle is searching the wrong folder for them.  somehow not using the working dir parameter correctly.
